# SPDX-FileCopyrightText: 2021-2024 Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: CC0-1.0

version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
    - linux
    - windows
    - darwin
    - freebsd
    - openbsd
    - netbsd
    main: ./cmd/apg
    binary: apg

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - vendor: Winni Neessen
    maintainer: Winni Neessen <wn@neessen.dev>
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux

dmg:
  - replace: true

universal_binaries:

report_sizes: true

signs:
  - artifacts: checksum

sboms:
  - artifacts: archive

gitea_urls:
  api: https://src.neessen.cloud/api/v1
  download: https://src.neessen.cloud
