# SPDX-FileCopyrightText: 2021-2024 Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: CC0-1.0

name: Go

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Go Binary (Darwin)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.26
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "apg"
          extra_files: LICENSE README.md
          sha256sum: true
          md5sum: false
          ldflags: '-s -w'
          project_path: ./cmd/apg/
