name: Go

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Go Binary (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm, arm64, ppc64le, s390x]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.26
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "apg"
          extra_files: LICENSE README.md
          sha256sum: true
          md5sum: false
          ldflags: '-s -w'
          project_path: ./cmd/apg/
